<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://www.example.org/ns/store"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://www.example.org/ns/fulfillment"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns1="http://www.example.org/ns/intorder"
                xmlns:client="http://xmlns.oracle.com/POApplication/POProcessing/FulfillmentPr"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/Application1/InStore/ManageInventory"
                xmlns:ns3="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns4="/orderssdo/common/types/"
                xmlns:ns5="/customersdo/common/types/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FulfillmentPr.wsdl"/>
        <oracle-xsl-mapper:rootElement name="FulFillmentRequest" namespace="http://www.example.org/ns/fulfillment"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="http://localhost:8001/soa-infra/services/default/InternalStore!1.0/ManageInventory.wsdl"/>
        <oracle-xsl-mapper:rootElement name="StoreRequest" namespace="http://www.example.org/ns/store"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN JUN 10 13:34:09 GST 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:StoreRequest>
      <xsl:for-each select="/ns0:FulFillmentRequest/ns1:items/ns1:item">
        <tns:product>
          <tns:prodId>
            <xsl:value-of select="ns1:prodId"/>
          </tns:prodId>
          <tns:qtyOrdered>
            <xsl:value-of select="ns1:qty"/>
          </tns:qtyOrdered>
        </tns:product>
      </xsl:for-each>
    </tns:StoreRequest>
  </xsl:template>
</xsl:stylesheet>
