<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CustomerSDOService"
     targetNamespace="/customersdo/common/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="/customersdo/common/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="CustomerService">
        <plnk:role name="CustomerSDOService" portType="tns:CustomerSDOService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="/customersdo/common/" location="http://localhost:8001/CustomerSDO/CustomerSDOService?WSDL"/>
</wsdl:definitions>
